package pl.edu.agh.soa.studentservice.helloconsumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-04-08T08:50:12.832+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://studentservice.soa.agh.edu.pl/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod(action = "say_hi")
    @RequestWrapper(localName = "hello", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.helloconsumer.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.helloconsumer.HelloResponse")
    @WebResult(name = "HelloResponse", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
