package pl.edu.agh.soa.studentservice.consumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-04-08T08:48:57.290+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://studentservice.soa.agh.edu.pl/", name = "StudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentService {

    @WebMethod(action = "get_student_by_id")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetStudentByIdResponse")
    @WebResult(name = "SingleStudent", targetNamespace = "")
    public pl.edu.agh.soa.studentservice.consumer.Student getStudentById(
        @WebParam(name = "studentId", targetNamespace = "")
        java.lang.String studentId
    );

    @WebMethod(action = "get_avatar")
    @RequestWrapper(localName = "getAvatarById", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetAvatarById")
    @ResponseWrapper(localName = "getAvatarByIdResponse", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetAvatarByIdResponse")
    @WebResult(name = "Avatar", targetNamespace = "")
    public byte[] getAvatarById(
        @WebParam(name = "studentId", targetNamespace = "")
        java.lang.String studentId
    );

    @WebMethod(action = "filter_students")
    @RequestWrapper(localName = "getFilteredStudents", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetFilteredStudents")
    @ResponseWrapper(localName = "getFilteredStudentsResponse", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetFilteredStudentsResponse")
    @WebResult(name = "FilteredStudentList", targetNamespace = "")
    public java.util.List<pl.edu.agh.soa.studentservice.consumer.Student> getFilteredStudents(
        @WebParam(name = "phrase", targetNamespace = "")
        java.lang.String phrase
    );

    @WebMethod(action = "list_all_students")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://studentservice.soa.agh.edu.pl/", className = "pl.edu.agh.soa.studentservice.consumer.GetStudentsResponse")
    @WebResult(name = "students", targetNamespace = "")
    public pl.edu.agh.soa.studentservice.consumer.GetStudentsResponse.Students getStudents();
}
